In [1]:
import plotly.graph_objects as go

In [5]:
#Pip install plotly
import plotly.graph_objects as go

# Data definition
years = [2018, 2019, 2020, 2021, 2022]
sales = [100, 150, 200, 180, 220]

# (Scatter Plot)
fig = go.Figure(data = go.Scatter(x = years, y = sales))
fig.show()

In [6]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [8]:
path = 'train.csv'
df = pd.read_csv(path)

df.drop(['PassengerId','Name','Ticket'], axis=1,inplace=True)

In [9]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [10]:
def chk_types(df):
    dtypes =df.dtypes
    n_unique = df.nunique()
    return pd.DataFrame({"Dtypes":dtypes,"Num_uniques":n_unique}).T

In [11]:
chk_types(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes,int64,int64,object,float64,int64,int64,float64,object,object
Num_uniques,2,3,2,88,7,7,248,147,3

In [12]:
cols = ['Survived','Pclass','Parch','Sex','Embarked','SibSp']

df[cols] = df[cols].astype('category')
chk_types(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes,category,category,category,float64,category,category,float64,object,category
Num_uniques,2,3,2,88,7,7,248,147,3

In [13]:
null = df.isnull().sum()
ratio = round( (null /df.shape[0])*100 ,2).astype(str) +"%"
pd.DataFrame({"Null_sum": null, "Ratio %": ratio}).T

         Survived Pclass   Sex     Age SibSp Parch  Fare  Cabin Embarked
Null_sum        0      0     0     177     0     0     0    687        2
Ratio %      0.0%   0.0%  0.0%  19.87%  0.0%  0.0%  0.0%  77.1%    0.22%

In [14]:
df1 = df.dropna(subset=['Embarked'], inplace= True)
df2 = df.drop("Cabin", axis=1, inplace= True)

In [15]:
median =  df['Age'].median()
df['Age'].fillna(median, inplace= True)

In [16]:
null = df.isnull().sum()
ratio = round( (null /df.shape[0])*100 ,2).astype(str) +"%"
pd.DataFrame({"Null_sum": null, "Ratio %": ratio}).T

         Survived Pclass   Sex   Age SibSp Parch  Fare Embarked
Null_sum        0      0     0     0     0     0     0        0
Ratio %      0.0%   0.0%  0.0%  0.0%  0.0%  0.0%  0.0%     0.0%